# Change these first
owner: Error063 # Your GitHub organization or username, where this repository lives
repo: mai-status # The name of this repository

sites:
  - name: 标题服务器
    check: "tcp-ping"
    url: maimai-gm.wahlap.com
    port: 42081
  - name: 会员服务器
    check: "tcp-ping"
    url: at.sys-all.cn
    port: 80
  - name: Net认证
    check: "tcp-ping"
    url: ai.sys-all.cn
    port: 80
  - name: 玩家二维码
    check: "tcp-ping"
    url: wq.sys-all.cn
    port: 80
  - name: 舞萌Net
    url: https://maimai.wahlap.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: mai-status.wahleak.tech
  # baseUrl: /your-repo-name
  logoUrl: https://img.picui.cn/free/2024/06/11/66684d36eee0c.png
  name: 今天舞萌痴们能不能玩舞萌DX
  introTitle: "今天舞萌痴们能不能玩舞萌DX"
  introMessage: 当前页面使用GitHub Actions对舞萌DX各个API涉及到的服务器进行访问测试，所有结果仅供参考
  navbar:
    - title: 状态
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
